main:
  - name: Home
    url: '/#'
    weight: 1
  - name: Posts
    url: /posts/
    weight: 2
  - name: Docs
    url: /docs/
    weight: 3
  - name: Projects
    url: /projects/
    weight: 4
  - name: Categories
    url: /categories/
    weight: 5
  - name: Tags
    url: /tags/
    weight: 6